[package]
name = "util"
version = "0.1.0"
authors = ["Michael Rose <elementation@gmail.com>"]

[dependencies]
failure = "0.1"
regex = "*"
itertools = "0.10"
streaming-stats = "0.1"
noisy_float = "0.1.2"
